USE [master]
GO

/****** Object:  Database [CSDL_ChanNuoi]    Script Date: 1/14/2023 5:58:11 PM ******/
CREATE DATABASE [CSDL_ChanNuoi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CSDL_ChanNuoi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CSDL_ChanNuoi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CSDL_ChanNuoi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CSDL_ChanNuoi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CSDL_ChanNuoi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ARITHABORT OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET RECOVERY FULL 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET  MULTI_USER 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CSDL_ChanNuoi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CSDL_ChanNuoi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CSDL_ChanNuoi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CSDL_ChanNuoi] SET  READ_WRITE 
GO

